"""
Step: figures

Publication-quality figures, generated BY the pipeline from the
committed step results -- every figure in the paper regenerates from
one command, with no hand-edited screenshots.

Design rules applied throughout: one model = one fixed color (never
re-assigned between figures), one axis per panel, neutral gray for the
real-data references (train/holdout/noise floors), direct legends, and
a colorblind-validated categorical palette.

Each figure is saved as PNG (for viewing) and PDF (for the manuscript).
A missing input file skips that figure with a note instead of failing
the step.
"""

import json
import os

from pipeline.config import PipelineConfig
from pipeline.steps.base import PipelineStep

# Fixed, validated categorical assignment (never cycled or re-ranked).
MODEL_COLORS = {
    "tvae": "#2a78d6",             # blue
    "ctgan": "#eb6834",            # orange
    "gaussian_copula": "#1baf7a",  # aqua
    "mst": "#eda100",              # yellow
    "dpctgan": "#e87ba4",          # magenta
    "aim": "#008300",              # green
    # extended-plan variants (see PipelineConfig.extended_plan); absent
    # runs simply produce no series. Prefix matching in _model_of is
    # longest-first, so these win over their base names.
    "tvae_qt": "#7fb3e8",          # light blue
    "tvae_cap256": "#8e6bc8",      # purple
    "tvae_ep1000": "#17becf",      # cyan
    "tvae_ind": "#1d4f8c",         # dark blue
    "ctgan_qt": "#f3a983",         # light orange
    "aim40": "#66b032",            # light green
    "ddpm": "#7a4a21",             # brown (in-house diffusion baseline)
    "ddpm_g": "#b8860b",           # dark gold (logic-guided diffusion)
    "patectgan": "#c05fbe",        # violet (second DP-GAN framework)
}
REAL_COLOR = "#444444"
FLOOR_COLOR = "#888888"


class FiguresStep(PipelineStep):
    name = "figures"

    def run(self, config: PipelineConfig) -> None:
        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.pyplot as plt

        plt.rcParams.update({
            "figure.dpi": 200, "savefig.dpi": 200, "font.size": 9,
            "axes.spines.top": False, "axes.spines.right": False,
            "axes.grid": True, "grid.alpha": 0.25, "grid.linewidth": 0.5,
            "legend.frameon": False,
        })

        self.out_dir = config.step_dir(self.name)
        os.makedirs(self.out_dir, exist_ok=True)
        self.config = config

        # A missing input file is a documented skip; any OTHER failure is
        # collected and raised at the END, so every figure still gets
        # attempted but a silently dropped paper figure fails the step.
        failures = []
        for fig_fn in (self._fig_epsilon_curves, self._fig_tstr, self._fig_ks_profiles,
                       self._fig_dcr, self._fig_km, self._fig_coherence,
                       self._fig_c2st, self._fig_mia):
            try:
                fig_fn(plt)
            except FileNotFoundError as e:
                print(f"⚠️  Skipping {fig_fn.__name__}: missing input ({e})")
            except Exception as e:
                print(f"⚠️  {fig_fn.__name__} failed: {type(e).__name__}: {e}")
                failures.append(f"{fig_fn.__name__}: {type(e).__name__}: {e}")

        print(f"Figures written to {self.out_dir}")
        if failures:
            raise RuntimeError(
                f"{len(failures)} figure(s) failed (all figures were still "
                "attempted): " + "; ".join(failures))

    # --- helpers ---

    def _load(self, step: str, filename: str) -> dict:
        path = os.path.join(self.config.step_dir(step), filename)
        if not os.path.exists(path):
            raise FileNotFoundError(path)
        with open(path) as f:
            return json.load(f)

    def _save(self, plt, fig, name: str) -> None:
        for ext in ("png", "pdf"):
            fig.savefig(os.path.join(self.out_dir, f"{name}.{ext}"), bbox_inches="tight")
        plt.close(fig)
        print(f"  saved {name}.png/.pdf")

    @staticmethod
    def _model_of(run_id: str) -> str:
        for m in sorted(MODEL_COLORS, key=len, reverse=True):
            if run_id.startswith(m):
                return m
        return run_id

    @classmethod
    def _display_label(cls, run_id: str) -> str:
        """Compact legend label: model name plus epsilon where present.
        One representative run per model is plotted, so the seed suffix
        is noise in a legend ('gaussian_copula_seed0' -> 'copula')."""
        import re

        model = cls._model_of(run_id)
        short = {"gaussian_copula": "copula"}.get(model, model)
        m = re.search(r"_eps(\d+)(?:p(\d+))?_", run_id + "_")
        if m:
            eps = m.group(1) + ("." + m.group(2) if m.group(2) else "")
            return f"{short} (ε={eps})"
        return short

    # --- figures ---

    def _fig_epsilon_curves(self, plt):
        ev = self._load("evaluate", "DT4H_Evaluation.json")
        floor = next(c for c in ev["comparisons"] if c.get("pair") == "train vs holdout")["aggregates"]
        groups = ev.get("groups", [])
        metrics = [("tvd_mean", "TVD mean (categorical)", floor["tvd"].get("mean")),
                   ("ks_mean", "KS mean (numeric)", floor["ks"].get("mean")),
                   ("missing_rate_mad", "missingness MAD", floor["missing_rate_mean_abs_diff"])]
        fig, axes = plt.subplots(1, 3, figsize=(10.5, 3.4))
        dp_models = sorted({g["synthesizer"] for g in groups if g.get("epsilon") is not None})
        for ax, (key, label, floor_v) in zip(axes, metrics):
            for m in dp_models:
                pts = sorted([(g["epsilon"], g[key]["mean"], g[key].get("sd"))
                              for g in groups
                              if g["synthesizer"] == m and g.get("epsilon") is not None
                              and g.get(key)], key=lambda p: p[0])
                if pts:
                    display = {"aim": "aim (50-col subset)",
                               "aim40": "aim (40-col subset)"}.get(m, m)
                    ax.errorbar([p[0] for p in pts], [p[1] for p in pts],
                                yerr=[(p[2] or 0.0) for p in pts],
                                fmt="o-", color=MODEL_COLORS.get(m, "#999"),
                                label=display, linewidth=2, markersize=4,
                                capsize=2, elinewidth=1)
            if floor_v is not None:
                ax.axhline(floor_v, color=FLOOR_COLOR, linestyle="--", linewidth=1,
                           label="sampling-noise floor")
            ax.set_xlabel("ε (privacy budget)")
            ax.set_title(label, fontsize=9)
            ax.set_xscale("log")
            # Log fidelity axis: the sweep's story is MST/AIM saturating AT
            # the floor while DP-CTGAN sits 40x above it -- on a linear axis
            # every near-floor curve collapses into one band at the bottom.
            ax.set_yscale("log")
            eps_values = sorted({g["epsilon"] for g in groups
                                 if g.get("epsilon") is not None})
            ticks = ([0.5] if 0.5 in eps_values else []) + [1, 5, 10, 20]
            ax.set_xticks(ticks)
            ax.set_xticklabels([f"{t:g}" for t in ticks])
        # One shared legend in RESERVED space below the panels: an in-panel
        # box collides with the curves, and a negative-anchor overlay
        # collides with the x-axis labels.
        fig.subplots_adjust(bottom=0.30, top=0.82, wspace=0.28)
        handles, labels = axes[0].get_legend_handles_labels()
        fig.legend(handles, labels, loc="lower center", ncol=4, fontsize=8,
                   bbox_to_anchor=(0.5, 0.01))
        fig.suptitle("Privacy-utility trade-off: fidelity vs ε (lower is better)", y=0.96)
        self._save(plt, fig, "fig_epsilon_curves")

    def _fig_tstr(self, plt):
        ut = self._load("utility", "DT4H_Utility_TSTR.json")
        groups = [g for g in ut.get("grouped_auc_gap", [])]
        if not groups:
            raise FileNotFoundError("no grouped utility results")
        labels, gaps, sds, colors, single = [], [], [], [], []
        for g in sorted(groups, key=lambda g: g["mean_gap"]):
            short = {"gaussian_copula": "copula"}.get(g["synthesizer"], g["synthesizer"])
            eps = f" (ε={g['epsilon']:g})" if g.get("epsilon") is not None else ""
            # Single-run groups have NO sd (not an sd of 0): they get no
            # error bar and an asterisked label instead of a fake ±0.
            is_single = g.get("sd_gap") is None
            labels.append(f"{short}{eps}" + ("*" if is_single else ""))
            gaps.append(g["mean_gap"])
            sds.append(0.0 if is_single else g["sd_gap"])
            single.append(is_single)
            colors.append(MODEL_COLORS.get(g["synthesizer"], "#999"))
        fig, ax = plt.subplots(figsize=(6, 0.36 * len(labels) + 1.2))
        y = range(len(labels))
        # Error bars only where an sd exists; sd=0 keeps its (zero-length)
        # whisker so it stays visually distinct from "no sd available".
        xerr = [[0.0 if s else sd for sd, s in zip(sds, single)],
                [0.0 if s else sd for sd, s in zip(sds, single)]]
        ax.barh(y, gaps, xerr=xerr, color=colors, height=0.62, error_kw={"linewidth": 1})
        for yi, gap, sd in zip(y, gaps, sds):
            # value label beyond the bar end (and its error whisker)
            x = gap + sd + 0.004 if gap >= 0 else gap - sd - 0.004
            ax.text(x, yi, f"{gap:+.3f}", va="center",
                    ha="left" if gap >= 0 else "right", fontsize=7, color="#444444")
        ax.set_yticks(list(y))
        ax.set_yticklabels(labels, fontsize=8)
        ax.axvline(0, color=REAL_COLOR, linewidth=1)
        lo, hi = min(gaps), max(g + s for g, s in zip(gaps, sds))
        ax.set_xlim(lo - 0.03, hi + 0.03)
        ax.set_xlabel("TSTR AUC gap vs real-data baseline (lower is better)")
        ax.set_title("Downstream utility: train-synthetic, test-real (holdout)")
        ax.invert_yaxis()
        if any(single):
            fig.text(0.01, -0.03, "* single run: sd not available, no error bar "
                     "(bars with whiskers show ± sd across runs; a zero-length "
                     "whisker is an observed sd of 0).",
                     fontsize=6.5, color="#666666", ha="left")
        self._save(plt, fig, "fig_tstr_gaps")

    def _fig_ks_profiles(self, plt):
        ev = self._load("evaluate", "DT4H_Evaluation.json")
        floor_cmp = next(c for c in ev["comparisons"] if c.get("pair") == "train vs holdout")
        reps = self._representative_runs(ev)
        fig, ax = plt.subplots(figsize=(6.2, 3.5))
        floor_ks = sorted(r["ks_statistic"] for r in floor_cmp["numeric"])
        import numpy as np

        def _ecdf(values):
            """Proper ECDF: steps, anchored at (0, 0) and extended to the
            right edge at 1.0 -- a curve that stops mid-plot reads as
            clipped data."""
            xs = np.concatenate([[0.0], np.sort(values), [1.0]])
            ys = np.concatenate([[0.0], np.arange(1, len(values) + 1) / len(values), [1.0]])
            return xs, ys

        xs, ys = _ecdf(np.asarray(floor_ks))
        ax.plot(xs, ys, color=FLOOR_COLOR, linestyle="--", linewidth=1.5,
                drawstyle="steps-post", label="noise floor\n(train vs holdout)")
        for run_id in reps:
            c = next((x for x in ev["comparisons"] if x.get("run_id") == run_id), None)
            if not c:
                continue
            ks = [r["ks_statistic"] for r in c["train_vs_synthetic"]["numeric"]]
            m = self._model_of(run_id)
            xs, ys = _ecdf(np.asarray(ks))
            ax.plot(xs, ys, color=MODEL_COLORS.get(m, "#999"), linewidth=2,
                    drawstyle="steps-post", label=self._display_label(run_id))
        ax.set_xlim(0, 1.0)
        ax.set_ylim(0, 1.02)
        ax.set_xlabel("per-column KS statistic")
        ax.set_ylabel("fraction of numeric columns ≤ x")
        ax.set_title("Numeric fidelity profile vs the sampling-noise floor")
        # Legend outside the axes: every in-plot position collides with a curve.
        ax.legend(fontsize=7.5, loc="center left", bbox_to_anchor=(1.02, 0.5))
        self._rep_caption(fig)
        self._save(plt, fig, "fig_ks_profiles")

    def _fig_dcr(self, plt):
        pv = self._load("privacy", "DT4H_Privacy_Assessment.json")
        base = pv["holdout_baseline"].get("dcr_histogram")
        if not base:
            raise FileNotFoundError("privacy JSON has no histogram data (rerun privacy step)")
        import numpy as np

        fig, ax = plt.subplots(figsize=(6.6, 3.2))
        edges = np.asarray(base["bin_edges"])
        centers = (edges[:-1] + edges[1:]) / 2
        b = np.asarray(base["counts"], float)
        ax.fill_between(centers, b / b.sum(), step="mid", alpha=0.35, color=REAL_COLOR,
                        label="real unseen patients\n(holdout→train)")
        # x-limit follows the data: the rightmost bin edge with any mass
        # across every plotted histogram (a hardcoded limit clipped or
        # wasted space depending on the run set).
        occupied = edges[1:][b > 0]
        max_x = float(occupied.max()) if occupied.size else float(edges[-1])
        reps = [r["run_id"] for r in pv["runs"]
                if r["run_id"] in self._representative_ids({r2["run_id"] for r2 in pv["runs"]})]
        for r in pv["runs"]:
            if r["run_id"] not in reps or not r.get("dcr_histogram"):
                continue
            h = np.asarray(r["dcr_histogram"]["counts"], float)
            occupied = edges[1:len(h) + 1][h > 0]
            if occupied.size:
                max_x = max(max_x, float(occupied.max()))
            m = self._model_of(r["run_id"])
            ax.plot(centers, h / h.sum(), color=MODEL_COLORS.get(m, "#999"),
                    linewidth=2, label=self._display_label(r["run_id"]),
                    drawstyle="steps-mid")
        p5 = pv["holdout_baseline"]["dcr_p5"]
        ax.axvline(p5, color=FLOOR_COLOR, linestyle="--",
                   linewidth=1, label="holdout p5\n(risk threshold)")
        ax.set_xlim(0, max(max_x, float(p5)) * 1.05)
        ax.set_xlabel("distance to closest training record (DCR)")
        ax.set_ylabel("share of records")
        ax.set_title("Privacy: synthetic records vs the unseen-patient baseline")
        # Legend outside the axes: the in-plot box overlapped the histograms.
        ax.legend(fontsize=7.5, loc="center left", bbox_to_anchor=(1.02, 0.5))
        self._rep_caption(fig)
        self._save(plt, fig, "fig_dcr")

    def _fig_km(self, plt):
        sv = self._load("survival", "DT4H_Survival_Fidelity.json")
        endpoints = sv.get("endpoints", {})
        if not endpoints:
            raise FileNotFoundError("no endpoints in survival JSON")
        fig, axes = plt.subplots(1, len(endpoints), figsize=(5.2 * len(endpoints), 3.4),
                                 squeeze=False)
        for ax, (name, e) in zip(axes[0], endpoints.items()):
            reps = self._representative_ids(set(e["curves"]) - {"train", "holdout"})
            for rid in ("train", "holdout"):
                c = e["curves"].get(rid)
                if c:
                    ax.plot([g / 365 for g in c["grid_days"]], c["survival"],
                            color=REAL_COLOR, linewidth=2,
                            linestyle="-" if rid == "train" else "--", label=f"real {rid}")
            for rid in sorted(reps):
                c = e["curves"].get(rid)
                if not c:
                    continue
                m = self._model_of(rid)
                ax.plot([g / 365 for g in c["grid_days"]], c["survival"],
                        color=MODEL_COLORS.get(m, "#999"), linewidth=1.8,
                        label=self._display_label(rid))
            ax.set_xlabel("years since index admission")
            ax.set_ylabel("event-free probability")
            ax.set_ylim(0, 1.02)
            ax.set_title(name.replace("_", " "), fontsize=9)
            # Survival curves stay in the upper band, so the lower-left
            # corner is the one region an in-axes legend cannot overlap.
            ax.legend(fontsize=6.5, loc="lower left", ncol=2)
        fig.suptitle("Kaplan-Meier fidelity (nulls = censored at 5 years)", y=1.04)
        self._rep_caption(fig)
        self._save(plt, fig, "fig_km_curves")

    def _fig_coherence(self, plt):
        co = self._load("coherence", "DT4H_Coherence_Audit.json")
        frames = co["frames"]
        reps = self._representative_ids({f.get("run_id") for f in frames if f.get("run_id")})
        rows = [f for f in frames if f["frame"].startswith(("train", "holdout"))
                or f.get("run_id") in reps]
        fig, ax = plt.subplots(figsize=(6, 0.38 * len(rows) + 1))
        labels, vals, colors = [], [], []
        for f in rows:
            labels.append(f["frame"].replace("synthetic[", "").rstrip("]"))
            vals.append(f["overall_violation_rate"] or 0.0)
            m = self._model_of(f.get("run_id") or "")
            colors.append(REAL_COLOR if f.get("run_id") is None else MODEL_COLORS.get(m, "#999"))
        y = range(len(labels))
        ax.barh(y, vals, color=colors, height=0.62)
        ax.set_yticks(list(y))
        ax.set_yticklabels(labels, fontsize=8)
        ax.set_xlabel("rule-violation rate (real frames = fair baseline)")
        ax.set_title("Row-level clinical coherence")
        ax.invert_yaxis()
        self._rep_caption(fig)
        self._save(plt, fig, "fig_coherence")

    def _fig_c2st(self, plt):
        ev = self._load("evaluate", "DT4H_Evaluation.json")
        runs = [(c["run_id"], c["c2st_auc"]) for c in ev["comparisons"] if "c2st_auc" in c]
        if not runs:
            raise FileNotFoundError("no c2st results")
        reps = self._representative_ids({r for r, _ in runs})
        runs = sorted([r for r in runs if r[0] in reps], key=lambda r: r[1])
        fig, ax = plt.subplots(figsize=(6, 0.36 * len(runs) + 1.1))
        y = range(len(runs))
        ax.barh(y, [v for _, v in runs],
                color=[MODEL_COLORS.get(self._model_of(r), "#999") for r, _ in runs],
                height=0.62)
        ax.axvline(0.5, color=REAL_COLOR, linewidth=1, label="indistinguishable (0.5)")
        floor = ev.get("c2st_floor_train_vs_holdout")
        if floor:
            ax.axvline(floor, color=FLOOR_COLOR, linestyle="--", linewidth=1,
                       label=f"real-vs-real floor ({floor})")
        for yi, (_, v) in zip(y, runs):
            ax.text(v - 0.008, yi, f"{v:.2f}", va="center", ha="right",
                    fontsize=7.5, color="white", fontweight="bold")
        ax.set_yticks(list(y))
        ax.set_yticklabels([self._display_label(r) for r, _ in runs], fontsize=8)
        ax.set_xlim(0.4, 1.02)
        ax.set_xlabel("C2ST AUC (full-joint distinguishability)")
        ax.set_title("Can a classifier tell synthetic rows from real ones?")
        # Bars reach the right edge, so any in-axes legend overlaps a bar:
        # place it below the axes instead.
        ax.legend(fontsize=7.5, loc="upper center", bbox_to_anchor=(0.5, -0.22),
                  ncol=2)
        ax.invert_yaxis()
        self._rep_caption(fig)
        self._save(plt, fig, "fig_c2st")

    def _fig_mia(self, plt):
        at = self._load("attacks", "DT4H_Privacy_Attacks.json")
        runs = at.get("runs", [])
        if not runs:
            raise FileNotFoundError("no attack results")
        fig, ax = plt.subplots(figsize=(6, 0.32 * len(runs) + 1.1))
        labels, aucs, err_lo, err_hi, colors = [], [], [], [], []
        for r in sorted(runs, key=lambda r: r["membership_inference"]["attack_auc"]):
            m = r["membership_inference"]
            labels.append(r["run_id"])
            aucs.append(m["attack_auc"])
            err_lo.append(m["attack_auc"] - m["attack_auc_ci95"][0])
            err_hi.append(m["attack_auc_ci95"][1] - m["attack_auc"])
            colors.append(MODEL_COLORS.get(self._model_of(r["run_id"]), "#999"))
        y = range(len(labels))
        ax.errorbar(aucs, list(y), xerr=[err_lo, err_hi], fmt="none",
                    ecolor=REAL_COLOR, elinewidth=1, capsize=2)
        ax.scatter(aucs, list(y), c=colors, s=24, zorder=3)
        ax.axvline(0.5, color=FLOOR_COLOR, linestyle="--", linewidth=1,
                   label="no membership leakage (0.5)")
        ax.set_yticks(list(y))
        ax.set_yticklabels(labels, fontsize=7)
        ax.set_xlabel("membership-inference attack AUC (95% CI)")
        ax.set_title("Adversarial membership inference")
        ax.legend(fontsize=7)
        self._save(plt, fig, "fig_mia")

    # --- representative-run selection ---

    # Stated on every figure that overlays one run per model.
    REP_RULE = ("one run per model: seed 0; DP models at ε=15 where present, "
                "else the numerically largest completed ε")

    @staticmethod
    def _eps_of(run_id: str):
        """Numeric epsilon parsed from a run id ('eps20' -> 20.0,
        'eps0p5' -> 0.5), or None when the id carries no epsilon."""
        import re

        m = re.search(r"_eps(\d+)(?:p(\d+))?(?:_|$)", run_id)
        if not m:
            return None
        return float(m.group(1) + ("." + m.group(2) if m.group(2) else ""))

    def _rep_caption(self, fig) -> None:
        """Selection-rule note under a figure that shows representative
        runs only."""
        fig.text(0.01, -0.03, f"Shown: {self.REP_RULE}.",
                 fontsize=6.5, color="#666666", ha="left")

    def _representative_ids(self, run_ids: set) -> set:
        """One run per model for readable overlays: seed 0 for non-DP,
        headline ε=15 (or the NUMERICALLY largest completed ε -- a
        lexicographic sort would rank eps5 above eps20) at seed 0 for
        DP models."""
        reps = set()
        for m in MODEL_COLORS:
            candidates = [r for r in run_ids if r and self._model_of(r) == m]
            if not candidates:
                continue
            preferred = [r for r in candidates if r.endswith("_seed0")]
            pool = preferred or candidates
            headline = [r for r in pool if self._eps_of(r) == 15.0]
            if headline:
                reps.add(sorted(headline)[-1])
                continue
            with_eps = [(self._eps_of(r), r) for r in pool]
            eps_runs = [(e, r) for e, r in with_eps if e is not None]
            if eps_runs:
                reps.add(max(eps_runs)[1])
            else:
                reps.add(sorted(pool)[-1])
        return reps

    def _representative_runs(self, ev: dict) -> list:
        ids = {c["run_id"] for c in ev["comparisons"] if c.get("run_id")}
        return sorted(self._representative_ids(ids))
